server.port=8085

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=userServiceCB
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback/users