# Порт Eureka Server (стандартный для Eureka)
server.port=8761

# Имя приложения
spring.application.name=eureka-server

# Eureka Server сам НЕ должен регистрироваться как клиент
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false