server.port=8888
spring.application.name=config-server

# Читаем конфиги из локальной папки (native режим)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configs